version: '3'
services:
  appium:
    build: .
    ports:
      - "4723:4723"
    volumes:
      - .:/workspace
    networks:
      - test-network

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - test-network

  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    depends_on:
      - selenium-hub
    networks:
      - test-network

  firefox:
    image: selenium/node-firefox:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    depends_on:
      - selenium-hub
    networks:
      - test-network

  test-runner:
    image: openjdk:17-jdk-slim
    volumes:
      - .:/workspace
    working_dir: /workspace
  #   # command: ["sh", "-c", "javac -cp .:lib/* TestScript.java && java -cp .:lib/* TestScript"]
  #   command: ["sh", "-c", "javac TestScript.java && java TestScript"]
  # java-app:
  #   build: .
  #   container_name: java-hello-world
  #   depends_on:
  #     - appium
  #     - selenium-hub

networks:
  test-network:
    driver: bridge

