version: '3.8'
services:
  # appium:
  #   build: .
  #   ports:
  #     - "4723:4723"
  #   volumes:
  #     - .:/workspace
  #   networks:
  #     - test-network
  appium:
    image: appium/appium
    container_name: appium-server
    ports:
      - "4723:4723"
    environment:
      - APPIUM_ALLOW_INSECURE=chromedriver_autodownload
    volumes:
      - /dev/bus/usb:/dev/bus/usb # For USB devices (Linux only)
      - /dev/kvm:/dev/kvm         # For Android emulator (Linux only)

  android-emulator:
    image: selenium/node-chrome-debug
    container_name: android-emulator
    privileged: true
    ports:
      - "4444:4444" # Selenium Hub
      - "5900:5900" # VNC Server
    environment:
      - START_XVFB=false
      - MOBILE_PLATFORM=android
    depends_on:
      - appium
  maven:
    image: maven:3.8.5-openjdk-11
    container_name: maven-test-runner
    volumes:
      - ./tests:/usr/src/app # Your Maven project should be mounted here
      - ~/.m2:/root/.m2      # Cache Maven dependencies to speed up builds
    working_dir: /usr/src/app
    depends_on:
      - appium
    command: mvn clean test
 
networks:
  test-network:
    driver: bridge

